# Generated by Django 5.2 on 2025-04-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.FloatField()),
                ('typ', models.CharField(default='action', max_length=200)),
                ('image', models.ImageField(default='Images/None/Noimg.jpg', upload_to='Images')),
            ],
        ),
    ]
