# Generated by Django 5.2 on 2025-04-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
